logdir: 'results/Toy2D/TCVAE/'
logger: 
    type: base
    endwith: ['#']
# wandb_project_name: project name
# entity: entity name
model:
    arch: tcvae
    encoder:
        arch: tcvae_tcn_encoder
        FC_l_hidden: [434, 434,]
        FC_activation: ['elu', 'elu',]
        FC_out_activation: 'linear'
        TCN_kernel_size: 3
        TCN_num_channel_list: [18, 36, 72]
        time_step: 201
    decoder:
        arch: tcvae_tcn_decoder
        FCz_l_hidden: [434, 434,]
        FCz_activation: ['elu', 'elu',]
        FCz_out_dim: 36
        FCz_out_activation: 'linear'
        FCw_l_hidden: [434, 434,]
        FCw_activation: ['elu', 'elu',]
        FCw_out_activation: 'linear'
        FCw_out_dim: 72
        FC_l_hidden: [434, 434,]
        FC_activation: ['elu', 'elu',]
        FC_out_activation: 'linear'
        TCN_kernel_size: 3
        TCN_num_channel_list: [18, 36, 72]
        time_step: 201
    reg_type: auxillary
    reg_net:
        arch: fc_vec
        l_hidden: [256, 256,]
        activation: ['relu', 'relu']
        out_activation: 'linear'
    x_dim: 2
    z_dim: 1
    w_dim: 4
    beta: 1
    alpha: 1
data:
    training:
        seed: 10
        dataset: ToySpline2d
        root: datasets/toy_2d/
        batch_size: 75
        n_workers: 4
        split: training
        data_ratio: 1
        shuffle: True
        augmentation: True
    validation:
        dataset: ToySpline2d
        root: datasets/toy_2d/
        batch_size: 80
        n_workers: 4
        split: validation
        shuffle: True
    test:
        dataset: ToySpline2d
        root: datasets/toy_2d/
        batch_size: 40
        n_workers: 4
        split: test
        shuffle: True
trainer: base
training:
    n_epoch: 300000
    optimizer:
        name: 'adam'
        lr: 0.0001
        weight_decay: 0.001
    reg_optimizer:
        name: 'adam'
        lr: 0.0001
    lr_schedule: null
    resume: null
    augmentations: null
    print_interval: 5
    val_interval: 100
    visualize_interval: 10000
    save_epochs: 10000
    visualization:
        type: [Spline_2d_plot_recon, Spline_2d_mannor_mod]