logdir: 'results/Pouring/EMMP/AE/'
logger: 
    type: base
    endwith: ['#']
# wandb_project_name: project name
# entity: entity name
model:
    arch: emmp_ae 
    encoder:
        arch: fc_vec
        l_hidden: [168, 168]
        activation: ['elu', 'elu']
        out_activation: 'linear'
    decoder:
        arch: fc_se3
        l_hidden: [168, 168]
        activation: ['elu', 'elu']
        out_activation: 'linear'
    reg_type: independence
    alpha: 0.01
    x_dim: 5760
    z_dim: 2
    w_dim: 2
    recon_loss_fn_tr: MSE_loss_SE3
data:
    training:
        dataset: Pouring
        root: datasets/
        batch_size: 75
        n_workers: 4
        split: training
        augmentation: False
        skip_size: 1
        shuffle: True
    validation:
        dataset: Pouring
        root: datasets/
        batch_size: 75
        n_workers: 4
        split: validation
        skip_size: 1
        shuffle: True
    test:
        dataset: Pouring
        root: datasets/
        batch_size: 75
        n_workers: 4
        split: test
        skip_size: 1
        shuffle: True

trainer: base
training:
    n_epoch: 200000
    optimizer:
        name: 'adam'
        lr: 0.0001
        weight_decay: 0.001
    lr_schedule: null
    resume: null
    augmentations: null
    print_interval: 5
    val_interval: 100
    visualize_interval: 10000
    save_epochs: 10000
    visualization:
        type: [Pouring_recon_train_val]